runtime: nodejs8

handlers: 
  - url: /
    static_files: index.html
    upload: index\.html
    secure: always
  
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico
    secure: always

  - url: /style\.css
    static_files: style.css
    upload: style\.css
    secure: always

  - url: /main\.js
    static_files: main.js
    upload: main\.js
    secure: always
  
  - url: /img/
    static_dir: img
    secure: always
    