runtime: nodejs10

handlers: 
  - url: /
    static_files: index.html
    upload: index\.html
    secure: always

  - url: /data.json
    static_files: data.json
    upload: data\.json
    secure: always
  
  - url: /img/
    static_dir: img
    secure: always
  
  - url: /css/
    static_dir: css
    secure: always
  
  - url: /fotos/
    static_dir: fotos
    secure: always
  
  - url: /js/
    static_dir: js
    secure: always

  - url: /src/
    static_dir: src
    secure: always

  - url: /templates/
    static_dir: templates
    secure: always
  
  - url: /views/
    static_dir: views
    secure: always
  
  - url: /xjs/
    static_dir: xjs
    secure: always